" https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode
" https://milde.users.sourceforge.net/LUCR/Math/unimathsymbols.pdf
"
" m[aA] - m[zZ] are using the bold variants not the normal ones, fix this

let b:keymap_name = "math"

loadkeymap
;_0             ₀
;_1             ₁
;_2             ₂
;_3             ₃
;_4             ₄
;_5             ₅
;_6             ₆
;_7             ₇
;_8             ₈
;_9             ₉
;_+             ₊
;_-             ₋
;_=             ₌
;_(             ₍
;_)             ₎
;_a             ₐ
;_e             ₑ
;_h             ₕ
;_i             ᵢ
;_j             ⱼ
;_k             ₖ
;_l             ₗ
;_m             ₘ
;_n             ₙ
;_o             ₒ
;_p             ₚ
;_r             ᵣ
;_s             ₛ
;_t             ₜ
;_u             ᵤ
;_v             ᵥ
;_x             ₓ
;^0             ⁰
;^1             ¹
;^2             ²
;^3             ³
;^4             ⁴
;^5             ⁵
;^6             ⁶
;^7             ⁷
;^8             ⁸
;^9             ⁹
;^+             ⁺
;^-             ⁻
;^=             ⁼
;^(             ⁽
;^)             ⁾
;^a             ᵃ
;^b             ᵇ
;^c             ᶜ
;^d             ᵈ
;^e             ᵉ
;^f             ᶠ
;^g             ᵍ
;^h             ʰ
;^i             ⁱ
;^j             ʲ
;^k             ᵏ
;^l             ˡ
;^m             ᵐ
;^n             ⁿ
;^o             ᵒ
;^p             ᵖ
;^r             ʳ
;^s             ˢ
;^t             ᵗ
;^u             ᵘ
;^v             ᵛ
;^w             ʷ
;^x             ˣ
;^y             ʸ
;^z             ᶻ
;vdash          ⊢
;|-             ⊢
;vDash          ⊨
;dashv          ⊣
;-|             ⊣
;leq            ≤
;=<             ≤
;geq            ≥
;>=             ≥
;cup            ∪
;cap            ∩
;sqcup          ⊔
;sqcap          ⊓
;land           ∧
;wedge          ∧
;meet           ∧
;/\\            ∧
;lor            ∨
;vee            ∨
;join           ∨
;\\/            ∨
;neg            ¬
;not            <char-824>
;equiv          ≡
;==             ≡
;triangleq      ≜
;=^             ≜
;def            ≜
;doteq          ≐
;sim            ∼
;top            ⊤
;bot            ⊥
;in             ∈
;cong           ≅
;~=             ≅
;minus          −
;times          ⨯
;oplus          ⊕
;otimes         ⊗
;doubleplus     ⧺
;++             ⧺
;bob            ∻
;circ           ∘
;bullet         ∙
;cdot           ⋅
;ast            ∗
;rightarrow     →
;->             →
;leftarrow      ←
;<-             ←
;leftrightarrow ↔
;<->            ↔
;Rightarrow     ⇒
;=>             ⇒
;Leftarrow      ⇐
;<=             ⇐
;Leftrightarrow ⇔
;<=>            ⇔
;mapsto         ↦
;|->            ↦
;mapsfrom       ↤
;<-|            ↤
;hookrightarrow ↪
;hookleftarrow  ↩
;llbracket      ⟦
;[[             ⟦
;rrbracket      ⟧
;]]             ⟧
;langle         ⟨
;</             ⟨
;rangle         ⟩
;>/             ⟩
;subset         ⊂
;superset       ⊃
;horseshoe      ⊃
;subseteq       ⊆
;superseteq     ⊇
;sqsubset       ⊏
;sqsuperset     ⊐
;sqsubseteq     ⊑
;sqsuperseteq   ⊒
;infty          ∞
;forall         ∀
;exists         ∃
;emptyset       ∅
;doteq          ≐
;ldots          …
;...            …
;bN             ℕ
;bZ             ℤ
;bQ             ℚ
;bR             ℝ
;bC             ℂ
;mA             𝓐
;mB             𝓑
;mC             𝓒
;mD             𝓓
;mE             𝓔
;mF             𝓕
;mG             𝓖
;mH             𝓗
;mI             𝓘
;mJ             𝓙
;mK             𝓚
;mL             𝓛
;mM             𝓜
;mN             𝓝
;mO             𝓞
;mP             𝓟 
;mQ             𝓠
;mR             𝓡
;mS             𝓢
;mT             𝓣
;mU             𝓤
;mV             𝓥
;mW             𝓦
;mX             𝓧
;mY             𝓨
;mZ             𝓩
;ma             𝓪
;mb             𝓫
;mc             𝓬
;md             𝓭
;me             𝓮
;mf             𝓯
;mg             𝓰
;mh             𝓱
;mi             𝓲
;mj             𝓳
;mk             𝓴
;ml             𝓵
;mm             𝓶
;mn             𝓷
;mo             𝓸
;mp             𝓹
;mq             𝓺
;mr             𝓻
;ms             𝓼
;mt             𝓽
;mu             𝓾
;mv             𝓿
;mw             𝔀
;mx             𝔁
;my             𝔂
;mz             𝔃
;alpha          α
;beta           β
;gamma          γ
;Gamma          Γ
;delta          δ
;Delta          Δ
;epsilon        ε
;zeta           ζ
;eta            η
;theta          θ
;Theta          Θ
;kappa          κ
;lambda         λ
;Lambda         Λ
;mu             μ
;nu             ν
;xi             ξ
;Xi             Ξ
;pi             π
;Pi             Π
;rho            ρ
;sigma          σ
;Sigma          Σ
;tau            τ
;upsilon        υ
;phi            φ
;Phi            Φ
;chi            χ
;psi            ψ
;Psi            Ψ
;omega          ω
;Omega          Ω
;ell            ℓ
;hat            <char-770>
;gg             ≫
;>>             ≫
;ll             ≪
;<<             ≪
;box            □
;diamond        ◇
;bbox           ■
;bdiamond       ◆
;lax            ◯
;open           ◯
;closed         ⬤
;uparrow        ↑
;downarrow      ↓
;Uparrow        ⇑
;Downarrow      ⇓
;??             ❓
;cross          ❌
;check          ✅
;__             ─
;--             ╌
;..             ┈
;==             ═
;||             │
;blcorner       ╰
;brcorner       ╯
;tlcorner       ╭
;trcorner       ╮
;-o             ⊸
;multimap       ⊸
;triangleright  ▹
;triangleleft   ◃
;S              §
;nabla          ∇
;loz            ◊
;dag            †
;ddag           ‡
